### ISSUE TITLE
u-boot-denx_2016.01.bb

### ISSUE THREAD

**Issue by ZARk-be** [koenkooi/meta-beagleboard#27]
u-boot-denx_2016.01.bb is faulty

need to update to a more recent version of git rev

view thread : https://groups.google.com/forum/#!category-topic/beagleboard/beaglebone-black/hardware/u-boot/VMZs2yhs-Sw

Robert Nelson said it's a known bug in 2016.01 and was fixed since.

**Comment by imyller** [comment]
I agree. First release of 2016.01 does not boot.

I use following `u-boot-denx_2016.01.bbappend` until `meta-beagleboard` gets updated:

```bitbake
# v2016.01+ release tag
SRCREV = "161b1fe745394f34c4aa506edc964089785919f6"
```

This points to latest update commit made to v2016.01 and reliably boots the Beaglebone Black.
